import React, { useState } from 'react';
import axios from 'axios';
import RecipeCard from '../components/RecipeCard';

const DESSERT_CATEGORIES = [
  { label: 'All Desserts', icon: '🍰' },
  { label: 'Indian Sweets', icon: '🟡' },
  { label: 'Cakes & Pastries', icon: '🎂' },
  { label: 'Ice Cream & Frozen', icon: '🍦' },
  { label: 'Chocolate', icon: '🍫' },
  { label: 'Healthy Desserts', icon: '🥗' },
  { label: 'No-Bake Desserts', icon: '❄️' },
  { label: 'Traditional & Festive', icon: '🪔' },
];

const DESSERT_INGREDIENTS = [
  'Sugar', 'Brown sugar', 'Honey', 'Jaggery', 'Maple syrup', 'Condensed milk',
  'Milk', 'Heavy cream', 'Butter', 'Ghee', 'Cream cheese',
  'Flour', 'Whole wheat flour', 'Rice flour', 'Semolina', 'Besan',
  'Eggs', 'Vanilla extract', 'Baking powder', 'Baking soda',
  'Cocoa powder', 'Dark chocolate', 'Milk chocolate', 'White chocolate',
  'Almonds', 'Cashews', 'Pistachios', 'Walnuts', 'Raisins',
  'Mango', 'Banana', 'Strawberries', 'Blueberries', 'Coconut',
  'Paneer', 'Khoya', 'Curd', 'Yogurt', 'Greek yogurt',
  'Rose water', 'Cardamom', 'Saffron', 'Cinnamon', 'Nutmeg',
  'Gelatin', 'Agar agar', 'Cornstarch',
  'Oats', 'Dates', 'Peanut butter', 'Nutella',
  'Lemon', 'Orange', 'Coconut milk', 'Almond milk',
];

const LANGUAGES = [
  { code: 'English', label: '🇬🇧 English' },
  { code: 'Hindi', label: '🇮🇳 Hindi' },
  { code: 'Tamil', label: '🇮🇳 Tamil' },
  { code: 'Telugu', label: '🇮🇳 Telugu' },
  { code: 'Spanish', label: '🇪🇸 Spanish' },
  { code: 'French', label: '🇫🇷 French' },
];

function Desserts({ user }) {
  const [category, setCategory] = useState('All Desserts');
  const [ingredients, setIngredients] = useState([]);
  const [inputValue, setInputValue] = useState('');
  const [suggestions, setSuggestions] = useState([]);
  const [showDropdown, setShowDropdown] = useState(false);
  const [language, setLanguage] = useState('English');
  const [recipes, setRecipes] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [shareMsg, setShareMsg] = useState('');
  const [selectedRecipe, setSelectedRecipe] = useState(null);
  const [favourites, setFavourites] = useState(() => {
    try {
      const saved = localStorage.getItem('dessertFavourites');
      return saved ? JSON.parse(saved) : [];
    } catch { return []; }
  });

  const handleInputChange = (e) => {
    const value = e.target.value;
    setInputValue(value);
    if (value.trim().length > 0) {
      const filtered = DESSERT_INGREDIENTS.filter(ing =>
        ing.toLowerCase().includes(value.toLowerCase()) &&
        !ingredients.includes(ing)
      ).slice(0, 6);
      setSuggestions(filtered);
      setShowDropdown(true);
    } else {
      setSuggestions([]);
      setShowDropdown(false);
    }
  };

  const addIngredient = (value) => {
    const trimmed = (value || inputValue).trim();
    if (trimmed && !ingredients.includes(trimmed)) {
      setIngredients(prev => [...prev, trimmed]);
    }
    setInputValue('');
    setSuggestions([]);
    setShowDropdown(false);
  };

  const removeIngredient = (ing) => setIngredients(ingredients.filter(i => i !== ing));

  const generateDesserts = async () => {
    setError(''); setLoading(true); setRecipes([]);
    try {
      const response = await axios.post('http://localhost:5001/api/recipes/generate-desserts', {
        category,
        ingredients: ingredients.length > 0 ? ingredients : ['sugar', 'flour', 'butter', 'eggs', 'milk'],
        language,
      });
      setRecipes(response.data.recipes);
    } catch (err) {
      setError('Failed to generate desserts. Please try again!');
    }
    setLoading(false);
  };

  const handleShareRecipe = (recipe) => {
    const text = `🍰 Check out this dessert: ${recipe.name}!\n\n📝 ${recipe.description}\n\n🔥 Calories: ${recipe.calories} | 🍽️ Servings: ${recipe.servings}\n\n📲 Generated by Fridge to Fork AI`;
    try {
      const textArea = document.createElement('textarea');
      textArea.value = text;
      textArea.style.position = 'fixed';
      textArea.style.opacity = '0';
      document.body.appendChild(textArea);
      textArea.focus();
      textArea.select();
      document.execCommand('copy');
      document.body.removeChild(textArea);
      setShareMsg('✅ Dessert recipe copied! Paste anywhere to share 🎉');
    } catch (err) {
      setShareMsg('❌ Could not copy. Try again!');
    }
    setTimeout(() => setShareMsg(''), 3000);
  };

  const toggleFavourite = (recipe) => {
    const exists = favourites.find(f => f.name === recipe.name);
    const updated = exists ? favourites.filter(f => f.name !== recipe.name) : [...favourites, recipe];
    setFavourites(updated);
    localStorage.setItem('dessertFavourites', JSON.stringify(updated));
  };

  const isFavourite = (recipe) => favourites.some(f => f.name === recipe.name);

  const cardStyle = {
    backgroundColor: 'white', borderRadius: '20px', padding: '2rem',
    marginBottom: '1.5rem', boxShadow: '0 4px 20px rgba(74,124,47,0.08)',
    border: '1px solid #c8d8b0'
  };

  return (
    <div style={{ minHeight: '100vh', backgroundColor: '#f4f7ef' }}>
      <div style={{ maxWidth: '950px', margin: '0 auto', padding: '2rem' }}>

        {/* Header */}
        <div style={{ textAlign: 'center', marginBottom: '2rem' }}>
          <h1 style={{ fontSize: '2.5rem', fontWeight: '900', color: '#2d4a1e', marginBottom: '0.5rem' }}>
            🍰 Desserts & Sweets
          </h1>
          <p style={{ color: '#5a6e4a', fontSize: '1.1rem' }}>
            From gulab jamun to tiramisu — let AI create your perfect sweet treat!
          </p>
        </div>

        {/* Category Selector */}
        <div style={cardStyle}>
          <h2 style={{ fontWeight: '700', marginBottom: '1rem', color: '#1a2e10' }}>
            Step 1: Choose a Category 🎂
          </h2>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))', gap: '0.8rem' }}>
            {DESSERT_CATEGORIES.map((cat) => (
              <button key={cat.label} onClick={() => setCategory(cat.label)} style={{
                padding: '0.8rem', borderRadius: '12px',
                border: category === cat.label ? '2px solid #4a7c2f' : '2px solid #c8d8b0',
                backgroundColor: category === cat.label ? '#e8f0e0' : 'white',
                color: category === cat.label ? '#2d4a1e' : '#5a6e4a',
                cursor: 'pointer', fontWeight: '600', fontSize: '0.9rem',
                transition: 'all 0.2s'
              }}>
                {cat.icon} {cat.label}
              </button>
            ))}
          </div>
        </div>

        {/* Optional Ingredients */}
        <div style={cardStyle}>
          <h2 style={{ fontWeight: '700', marginBottom: '0.5rem', color: '#1a2e10' }}>
            Step 2: Add Ingredients (Optional) 🥛
          </h2>
          <p style={{ color: '#5a6e4a', fontSize: '0.9rem', marginBottom: '1rem' }}>
            Leave empty for AI to suggest desserts with common ingredients!
          </p>
          <div style={{ position: 'relative', marginBottom: '1rem' }}>
            <div style={{ display: 'flex', gap: '0.5rem' }}>
              <div style={{ position: 'relative', flex: 1 }}>
                <input
                  type="text" value={inputValue} onChange={handleInputChange}
                  onKeyDown={(e) => e.key === 'Enter' && addIngredient(inputValue)}
                  placeholder="e.g. chocolate, mango, condensed milk..."
                  style={{ width: '100%', padding: '0.8rem 1rem', borderRadius: '10px', border: '2px solid #c8d8b0', fontSize: '1rem', outline: 'none', backgroundColor: '#f7f9f4', boxSizing: 'border-box' }}
                />
                {showDropdown && suggestions.length > 0 && (
                  <div style={{ position: 'absolute', top: '100%', left: 0, right: 0, backgroundColor: 'white', borderRadius: '0 0 12px 12px', boxShadow: '0 8px 25px rgba(74,124,47,0.15)', border: '2px solid #4a7c2f', borderTop: 'none', zIndex: 1000, maxHeight: '200px', overflowY: 'auto' }}>
                    {suggestions.map((s, i) => (
                      <div key={i} onMouseDown={() => addIngredient(s)}
                        style={{ padding: '0.7rem 1rem', cursor: 'pointer', fontSize: '0.95rem', borderBottom: '1px solid #f0f4ea', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                        <span style={{ color: '#4a7c2f' }}>🍬</span> {s}
                      </div>
                    ))}
                  </div>
                )}
              </div>
              <button onClick={() => addIngredient(inputValue)} style={{
                background: 'linear-gradient(135deg, #2d4a1e, #4a7c2f)',
                color: 'white', border: 'none', borderRadius: '10px',
                padding: '0.8rem 1.5rem', cursor: 'pointer',
                fontWeight: '700', fontSize: '1rem',
                boxShadow: '0 3px 10px rgba(74,124,47,0.3)'
              }}>+ Add</button>
            </div>
          </div>
          {ingredients.length > 0 && (
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.5rem' }}>
              {ingredients.map((ing, i) => (
                <span key={i} style={{ backgroundColor: '#e8f0e0', color: '#2d4a1e', padding: '0.4rem 0.8rem', borderRadius: '50px', fontSize: '0.9rem', fontWeight: '600', border: '2px solid #c8d8b0', display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
                  {ing}
                  <span onClick={() => removeIngredient(ing)} style={{ cursor: 'pointer', color: '#dc2626', fontWeight: '800' }}>×</span>
                </span>
              ))}
            </div>
          )}
        </div>

        {/* Language */}
        <div style={cardStyle}>
          <h2 style={{ fontWeight: '700', marginBottom: '1rem', color: '#1a2e10' }}>Step 3: Language 🌍</h2>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.8rem' }}>
            {LANGUAGES.map((lang) => (
              <button key={lang.code} onClick={() => setLanguage(lang.code)} style={{
                padding: '0.6rem 1.2rem', borderRadius: '50px',
                border: language === lang.code ? '2px solid #4a7c2f' : '2px solid #c8d8b0',
                backgroundColor: language === lang.code ? '#e8f0e0' : 'white',
                color: language === lang.code ? '#2d4a1e' : '#5a6e4a',
                cursor: 'pointer', fontWeight: '600', fontSize: '0.9rem'
              }}>
                {lang.label}
              </button>
            ))}
          </div>
        </div>

        {error && (
          <div style={{ backgroundColor: '#fef2f2', color: '#dc2626', padding: '1rem', borderRadius: '10px', marginBottom: '1rem', border: '1px solid #fecaca', fontWeight: '600' }}>
            ⚠️ {error}
          </div>
        )}

        {shareMsg && (
          <div style={{ backgroundColor: '#f0fdf4', color: '#16a34a', padding: '1rem', borderRadius: '10px', marginBottom: '1rem', border: '1px solid #bbf7d0', fontWeight: '600', textAlign: 'center' }}>
            {shareMsg}
          </div>
        )}

        {/* Generate Button */}
        <button onClick={generateDesserts} disabled={loading} style={{
          width: '100%', padding: '1rem',
          background: loading ? '#a8c48a' : 'linear-gradient(135deg, #2d4a1e, #4a7c2f)',
          color: 'white', border: 'none', borderRadius: '12px',
          cursor: loading ? 'not-allowed' : 'pointer',
          fontWeight: '800', fontSize: '1.1rem', marginBottom: '2rem',
          boxShadow: '0 4px 15px rgba(74,124,47,0.3)'
        }}>
          {loading ? '⏳ AI is preparing your desserts...' : '🍰 Generate Dessert Recipes with AI'}
        </button>

        {loading && (
          <div style={{ textAlign: 'center', padding: '2rem' }}>
            <div style={{ fontSize: '3rem', marginBottom: '1rem' }}>🍰</div>
            <p style={{ color: '#4a7c2f', fontWeight: '700', fontSize: '1.1rem' }}>AI is whipping up your desserts...</p>
            <p style={{ color: '#5a6e4a' }}>This usually takes 10-20 seconds</p>
          </div>
        )}

        {recipes.length > 0 && (
          <div>
            <h2 style={{ textAlign: 'center', fontSize: '1.5rem', fontWeight: '800', marginBottom: '1.5rem', color: '#1a2e10' }}>
              🎉 Your AI Generated Desserts!
            </h2>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '1.5rem' }}>
              {recipes.map((recipe, index) => (
                <RecipeCard
                  key={index}
                  recipe={recipe}
                  onFavourite={toggleFavourite}
                  isFavourite={isFavourite(recipe)}
                  onSelectForChat={() => setSelectedRecipe(recipe)}
                  isSelected={selectedRecipe?.name === recipe.name}
                  onShare={handleShareRecipe}
                  user={user}
                />
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

export default Desserts;